apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
spec:
  progressDeadlineSeconds: 60
  replicas: 2
  selector:
    matchLabels:
      app: register-app
  strategy:
    rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
        - name: register-app
          image: testsysadmin8/register-app-pipeline:1.0.0-2
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
 
